DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMP_NAME VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(12),
  CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  DOB DATE,
  EMP_TYPE VARCHAR(1) NOT NULL
);